language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository 
    - sys-img-armeabi-v7a-android-22  # Android Image
    
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    - '.+'

before_install:
 - chmod +x gradlew
 - touch $HOME/.android/repositories.cfg
 - yes | sdkmanager "platforms;android-29"  # match value in build.gradle
 - yes | sdkmanager "build-tools;29.0.3"    # match value in build.gradle

script:
  - ./gradlew clean build